version: 2.1

jobs:
  build-linux:
    docker:
      - image: rocker/r-ver:latest
    steps:
      - checkout
      - run: R -e 'options(repos = "http://cran.us.r-project.org")'
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz

  build-osx:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install R
          command: |
            brew install r
      - run:
          name: Install dependencies and check package
          command: |
            R -e 'install.packages("devtools")'
            R -e 'devtools::install_deps(dep = TRUE)'
            R CMD build .
            R CMD check *tar.gz

workflows:
  build:
    jobs:
      - build-linux
      - build-osx

