version: 2.1

jobs:
  build-linux:
    docker:
      - image: rocker/r-ver:latest
    steps:
      - checkout
      - run: sudo apt-get install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      - run: R -e 'install.packages("devtools", repos = "http://cran.us.r-project.org")'
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE, repos = 'http://cran.us.r-project.org')"
      - run:
          name: Update system and install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y pandoc libxt6
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz

  build-osx:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install R
          command: |
            brew install r
      - run:
          name: Install dependencies and check package
          command: |
            R -e 'install.packages("devtools", repos = "http://cran.us.r-project.org")'
            R -e 'devtools::install_deps(dep = TRUE, repos = "http://cran.us.r-project.org")'
      - run: sudo apt-get update
      - run: sudo apt-get install -y pandoc libxt6
      - run:
          name: build package in osx
          command: |
            R CMD build .
            R CMD check *tar.gz

workflows:
  build:
    jobs:
      - build-linux
      - build-osx

