version: 2.1

jobs:
  build-linux:
    docker:
      - image: rocker/r-ver:latest  # You can choose a specific R version if you prefer
    steps:
      - checkout
      - run: Rscript -e 'install.packages("devtools")'  # Install devtools or other dependencies
      - run: Rscript -e 'devtools::install_deps(dependencies = TRUE)'
      - run: Rscript -e 'devtools::check()'

  build-osx:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install R
          command: |
            brew install r
      - run:
          name: Install dependencies and check package
          command: |
            Rscript -e 'install.packages("devtools")'  # Install devtools or other dependencies
            Rscript -e 'devtools::install_deps(dependencies = TRUE)'
            Rscript -e 'devtools::check()'

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-osx

